# Release the package on GitHub and publish it to PyPI. Runs on merge of a pull request into main or when manually
# triggered.

name: cd

on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or commit SHA to publish and tag"
        type: string
        required: true
      tag:
        description: "Tag for release"
        type: string
        required: true

jobs:
  release:
    if: "${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get package version
        id: version
        run: echo "::set-output name=package_version::$(python setup.py --version)"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
        with:
          commitish: ${{ inputs.ref }}
          tag_name: ${{ inputs.tag || steps.version.outputs.package_version }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false


  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install `build`
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
