# Build the package, publish it to PyPI, and release it on GitHub.

name: cd

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install `build`
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10


  release:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get package version
        id: version
        run: echo "::set-output name=package_version::$(python setup.py --version)"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
        with:
          tag_name: ${{ steps.version.outputs.package_version }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
